// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoOkhUKr2o4JzaZKDFHq7NLTBTO1VYxn4',
    appId: '1:276520827269:android:362f54269aca6c51b36cec',
    messagingSenderId: '276520827269',
    projectId: 'bloomcarenew',
    storageBucket: 'bloomcarenew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS2axj1btQK5VlWvhkS3OYdqkP5oZFmVQ',
    appId: '1:276520827269:ios:934524c83abdc462b36cec',
    messagingSenderId: '276520827269',
    projectId: 'bloomcarenew',
    storageBucket: 'bloomcarenew.firebasestorage.app',
    iosBundleId: 'com.example.bloomCare',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyh5HseL9MupDlHY7QkKxuH2vYcqQejtc',
    appId: '1:276520827269:web:c522008e816163fab36cec',
    messagingSenderId: '276520827269',
    projectId: 'bloomcarenew',
    authDomain: 'bloomcarenew.firebaseapp.com',
    storageBucket: 'bloomcarenew.firebasestorage.app',
    measurementId: 'G-4X4WXQJJFV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS2axj1btQK5VlWvhkS3OYdqkP5oZFmVQ',
    appId: '1:276520827269:ios:934524c83abdc462b36cec',
    messagingSenderId: '276520827269',
    projectId: 'bloomcarenew',
    storageBucket: 'bloomcarenew.firebasestorage.app',
    iosBundleId: 'com.example.bloomCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyh5HseL9MupDlHY7QkKxuH2vYcqQejtc',
    appId: '1:276520827269:web:895a925fa378807fb36cec',
    messagingSenderId: '276520827269',
    projectId: 'bloomcarenew',
    authDomain: 'bloomcarenew.firebaseapp.com',
    storageBucket: 'bloomcarenew.firebasestorage.app',
    measurementId: 'G-LV91TKZSXB',
  );

}